### PR TITLE
fix open folder

### PR DESCRIPTION
**Pull request by adridev**

### CODE REVIEW

**Comment by barryvdh** [comment]
Just be aware that `false === $meta` is not the same as `!$meta`, or is that change intentional? (`!$meta` is also true for empty array)

**Comment by adridev** [comment]
Is totally intentional, getMetadata() returns the metadata, false or exception and the exception is caught above. I don't know if empty array could be returned but in that case the result would be the same in the current code. let me review it.

**Comment by adridev** [comment]
I check all the common actions (update, duplicate, copy, paste, delete, create...) and all is woking well with S3 and local filesystems.

**Comment by adridev** [comment]
about the meta check, we can also add the empty meta case to return stat earlier. nothing will change at the moment but we will save the following checks over the meta array.

**Pull request merged**
