### PR TITLE
add `'autoload' => true,` into elFinder configuration

### PR DESCRIPTION
**Pull request by nao-pon**
ref.
- Studio-42/elFinder#1162
- Studio-42/elFinder@aa58030bf701a59ff62cbe6a2a3e346ff6a6b373
- Studio-42/elFinder@66a3e5f6b91312592b2f34ddc2175446fe8dcde2

### CODE REVIEW

**Comment by barryvdh** [comment]
Thanks! 
Do people need to upgrade their config or is this the default?

**Comment by nao-pon** [comment]
It is not default. People need to upgrade their config. However, I think it’s no cool. Do you have something good idea?

**Comment by barryvdh** [comment]
If it's not defined, assume true?

**Comment by nao-pon** [comment]
@barryvdh Thanks! No, it is `false`.

**Comment by barryvdh** [comment]
But why not let it default to true? Cause this is breaking for everyone who updates with composer and doesn't change the config, right?

**Comment by nao-pon** [comment]
I will abolish the "autoload" option so I decided to solve by using the "get_declared_classes()".

**Comment by barryvdh** [comment]
But the volume driver should always be autoloaded, right?

**Comment by nao-pon** [comment]
Yes, My [elFinder.class.php L.349-](https://github.com/Studio-42/elFinder/blob/66a3e5f6b91312592b2f34ddc2175446fe8dcde2/php/elFinder.class.php#L349-L354) plan is
```php
		// get declared classes
		$declaredClasses = array_flip(get_declared_classes());

		// "mount" volumes
		foreach ($opts['roots'] as $i => $o) {
			$class = 'elFinderVolume'.(isset($o['driver']) ? $o['driver'] : '');

			if (!empty($opts['autoload']) || isset($declaredClasses[$class]) || class_exists($class, true)) {
				$volume = new $class();
```

**Comment by barryvdh** [comment]
No, those classes should be always autoloaded. Otherwise, why would je set your config to use it.
With a composer, that sort of thing is always autoloaded, not declared before.

**Comment by nao-pon** [comment]
"autoload" option is not required. However, it was left so that it is not a useless processing even a little.

- `!empty($opts['autoload'])` for more lightly
- `isset($declaredClasses[$class])` for legacy classes
- `class_exists($class, true)` for error handling

"(false || false || true)", if auto-loading class dosen't have config "autoload"

(sorry my poor english.)

**Comment by barryvdh** [comment]
I think you're just making it complicated. The `class_exists` for existing classes is probably already optimized, better then what you are trying.

**Comment by nao-pon** [comment]
> The class_exists for existing classes is probably already optimized,

Oh! That's right! It was the following.

```php
<?php

function my_autoloader($class) {
    echo $class." checking ";
}

spl_autoload_register('my_autoloader');

class test {}

if (class_exists('test')) {
	echo "yes";
} else {
	echo "no";
}
```

**Results**
- PHP 5.5.30 - "yes" only
- PHP 5.6.13 - "yes" only
- PHP 7.0.0 - "yes" only

Truly thank you! :+1:

**Comment by barryvdh** [comment]
You're welcome. Could you tag a new release today, to prevent problems when users update? Thanks!

**Comment by nao-pon** [comment]
OK. I released elFinder 2.1.4 . Please revert this PR. Thanks!

**Comment by barryvdh** [comment]
Done, thanks!

**Comment by nao-pon** [comment]
:+1:

**Pull request merged**
