### PR TITLE
supports item ID based file system adapter

### PR DESCRIPTION
**Pull request by nao-pon**
Example ref. https://github.com/nao-pon/flysystem-google-drive

Note: $meta['filename'] defined in [League\Flysystem\Cached\Storage](https://github.com/thephpleague/flysystem-cached-adapter/blob/377476e416b0771433873b7a96ea6ca72f43de1c/src/Storage/AbstractCache.php#L332).

Thanks!

### CODE REVIEW

**Comment by barryvdh** [comment]
Thanks. This is just for Google Drive?

**Comment by nao-pon** [comment]
@barryvdh Thanks! Yes, elFinder 2.1.x nightly + barryvdh/elfinder-flysystem-driver@dev + nao-pon/flysystem-google-drive @dev is working fine. :+1: 

demo ref. http://hypweb.net/elFinder-nightly/demo/develop/#elf_fls3_Lw

**Comment by barryvdh** [comment]
Ok cool, let me know if you want a stable tag!

**Comment by nao-pon** [comment]
Sure! :laughing:

**Comment by nao-pon** [comment]
@barryvdh I released [nao-pon/flysystem-google-drive 1.0.0](https://github.com/nao-pon/flysystem-google-drive/releases) and elFinder 2.1.7 . :-)

**Comment by barryvdh** [comment]
Tagged v0.1.4

**Comment by nao-pon** [comment]
@barryvdh :clap:

**Pull request merged**
