### PR TITLE
cacheing hasdir and add option 'disableEnsureParentDirectories'

### PR DESCRIPTION
**Pull request by nao-pon**
**prototype quality**
* Enable　cache ｀hasDir｀result
* Disable-able `ensureParentDirectories` method (for item ID base adapter)

### CODE REVIEW

**Comment by barryvdh** [comment]
I'm not really sure what this does. Do we really need `hasDir()`?

**Comment by barryvdh** [comment]
Can't we just do this for _subdirs:

```php
protected function _subdirs($path)
    {
        $contents = $this->fs->listContents($path);

        $dirs = array_filter($contents, function($item){
            return $item['type'] == 'dir';
        });

        return ! empty($dirs);
    }
```

And to check if the folder/file exists:
```
try {
        $meta = $this->fs->getMetadata($path);
} catch (\Exception $e) {
       return array();
}
```

It seems that FTP and local are now returning true  on `has()` calls for directories. Do we still need the `hasDir` call?

**Comment by nao-pon** [comment]
There is an adapter that contains the value of the hasDir to metadata. (Such as [flysystem-google-drive](https://github.com/nao-pon/flysystem-google-drive/blob/master/src/GoogleDriveAdapter.php#L596-L602)). We can be the perfect cache that does not cause the API calls such adapter. Like a [demo site](http://studio-42.github.io/elFinder/#elf_flsgd_Lw).

**Comment by barryvdh** [comment]
Can't you just return `true` on the `has($dir)` call?

**Comment by nao-pon** [comment]
has($dir) is exists "$dir"? but hasDir($dir) is  Have "$dir" sub-dirctory?

**Comment by barryvdh** [comment]
Okay but checking the listContents() has the same effect, right? Both require an API call.

**Comment by barryvdh** [comment]
And for what reason do we need to check if they have subdirs?

**Comment by nao-pon** [comment]
On flysystem-google-drive, To optimize the API call gets the value of hasDir() in the target directory listContents().

> And for what reason do we need to check if they have subdirs?

If there is a sub-directory in the tree view of elFinder comes out a triangle icon.

**Comment by barryvdh** [comment]
It's just that we need a lot of extra stuff, just for the Google Drive stuff, because it's different then the other drivers..

**Comment by nao-pon** [comment]
I agree. I want to create something that corresponds to also other adapter hasDir. But does not have the time...

For GoogleDrive adapter chooses to pass adapter loaded with cached adapter.

Thanks! :laughing:

**Pull request closed without merging**
