### PR TITLE
Remove cache, change util, bump to v3

### PR DESCRIPTION
**Pull request by barryvdh**

### CODE REVIEW

**Comment by jnoordsij** [comment]
Thanks for looking into this! So far no immediate errors yet, but it's not quite working yet either for me:
- The `_subdirs` method is throwing exceptions on call, because the return type of `listContents` is now `DirectoryListing` instead of array, so the `array_filter` call fails. Replacing https://github.com/barryvdh/elfinder-flysystem-driver/blob/4c6ff7a50c558616bd36bf715e3e85dc6ee28707/src/Driver.php#L289 with `$contents = $this->fs->listContents($path)->toArray();` seems to fix this. (Maybe static analysis can find more of these kind of problems?)
- All root directory listings in my current elFinder setup (1 local drive + 1 s3 drive) are empty when using the new driver; making new files works perfectly fine and they are saved properly on their respective storages, but they also immediately disappear from the visual interface.

I'm afraid I won't be able to look into it much further over the next 1-2 weeks, but maybe after that I'll have some spare time to try and help with testing and bugfixing.

**Comment by promatik** [comment]
**Update on my previous message**

I **was able** to test the Flysystem Driver, and as @jnoordsij said nothing gets listed on ElFinder.

image

I'm able to create files and folders but it doesn't get in the view.

I found it very strange because apparently the issue is not in the Driver, the json response of the connector is apparently correct.

image

It includes the list with all files and folders, I compared this response with an older version of this and I couldn't find any difference.

**Comment by promatik** [comment]
Hi @barryvdh!
I have a question for you regarding this issues, I found out that by not using [`elfinder-flysystem-driver`](https://github.com/barryvdh/elfinder-flysystem-driver), elFinder works with local files, if the developer sets nothing on `roots`, [`laravel-elfinder`](https://github.com/barryvdh/laravel-elfinder) works just great;

image

My first question is; what's the usage of [`elfinder-flysystem-driver`](https://github.com/barryvdh/elfinder-flysystem-driver)?
And then; if [`laravel-elfinder`](https://github.com/barryvdh/laravel-elfinder) works just great without  [`elfinder-flysystem-driver`](https://github.com/barryvdh/elfinder-flysystem-driver), shouldn't the installation be optional?

**Comment by barryvdh** [comment]
Yes for local you don't need the flysystem driver. I'll make that optional.

**Comment by barryvdh** [comment]
I merged this as 0.4 for now (dev version) and created https://github.com/barryvdh/laravel-elfinder/tree/develop which support 9.x, which you can test with `composer require barryvdh/laravel-elfinder:dev-develop --prefer-source`

**Comment by barryvdh** [comment]
Follow-up on https://github.com/barryvdh/elfinder-flysystem-driver/pull/84
I've tested it on the local driver, not yet ftp/s3. But should be the same logic als all specific adapter code/plugins are removed.

**Pull request merged**
