### PR TITLE
fix open folder command

### PR DESCRIPTION
**Pull request by adridev**

### CODE REVIEW

**Comment by barryvdh** [comment]
I think it should probably return $stat there,

**Comment by adridev** [comment]
Yeah, the result is the same, it reaches the end of the method and returns $stat.

**Comment by barryvdh** [comment]
I'll have to check, I think there was a good reason to do this.

Can you check all actions? Eg. rename, copy, upload, delete etc, with aws +local?

**Comment by adridev** [comment]
Ok, I will try to get some time and add some testing to the Driver apart to the manual tests.

**Comment by barryvdh** [comment]
What was wrong?

**Comment by adridev** [comment]
Sorry @barryvdh I was moving all stuff to my team organization and I should have deleted the branch in my repo by accident. In a moment, I will create a new one from the organization repo. 

Sorry.

**Comment by adridev** [comment]
New PR for this issue #46

**Pull request closed without merging**
