### PR TITLE
`_stat()` performance optimization

### PR DESCRIPTION
**Pull request by nao-pon**

### CODE REVIEW

**Comment by barryvdh** [comment]
Not sure if the meta data is always the same and includes the same information.
I'll have to check.

Do you have a specific issue with a driver?

**Comment by nao-pon** [comment]
I rewritten. I checked copy adapter. It is too heavy, because `getTimestamp`, `getSize`, `getMimetype` call `getMetadata` and `getMetadata` call API every time.

**Comment by barryvdh** [comment]
Ok thanks! (And for your other PR's)

**Comment by nao-pon** [comment]
Thanks!
By the way, I have added cache function to the copy adapter. ( https://github.com/nao-pon/flysystem-copy/commit/4f764f405c7dd02c4874128b97884ee00c467ecc ) :smile:

**Comment by barryvdh** [comment]
You could also use a Cached Adapter (https://github.com/thephpleague/flysystem-cached-adapter):

http://flysystem.thephpleague.com/upgrade-to-1.0.0/

**Comment by nao-pon** [comment]
Oh! Thank you! I'll try it!

**Pull request merged**
