### PR TITLE
support adapter method `getUrl()` if exists

### PR DESCRIPTION
**Pull request by nao-pon**

### CODE REVIEW

**Comment by barryvdh** [comment]
Which adapters have these?

**Comment by nao-pon** [comment]
copy.com driver. I sent pull request https://github.com/thephpleague/flysystem-copy/pull/8 .

**Comment by barryvdh** [comment]
I'm not sure how reliable this is, because there are a lot of magic methods to call functions, like in plugins. And in cached adapters etc.
Perhaps use a try/catch to try to get the url?

**Comment by nao-pon** [comment]
@barryvdh Thanks!

It's right of you to say certainly. I'm thinking to use in the inherited class in my project.

try/catch is necessary!

**Comment by nao-pon** [comment]
That this was rejected, I misunderstood.

Is there a possibility merged by using try/cache?

**Comment by barryvdh** [comment]
I didn't say it was rejected, but could probably be simplified a bit. Maybe not checking the url but just the try catch

**Comment by barryvdh** [comment]
Hmm, let me think about this. Not really sure what the best way is. Usually extra functionality for Flysystem is provided with a plugin, so perhaps I could create a plugin for the url functionality.

**Comment by nao-pon** [comment]
Yet, I don't understand well about flysystem so I have expectations for your plugin!

**Comment by barryvdh** [comment]
I've added a Plugin which does pretty much the same. Not really good yet, I'd rather check if an actual implementation has a specific method, so you know what to expect, instead of blindly calling getUrl().

I didn't really test this much, because I don't use Copy.com or other drivers that have public urls.. Can you give it a try?

**Comment by nao-pon** [comment]
It's great! I tested.. worked fine. But it need set  $stat['url']=1 in _stat() for call getUrl().

**Comment by nao-pon** [comment]
How about #7

**Pull request closed without merging**
